# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Math',
            new_name='MathQuestion',
        ),
    ]
