# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_mathanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathanswer',
            name='solver',
            field=models.CharField(max_length=50),
        ),
    ]
