# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170506_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquestion',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
