# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20170720_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologyquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemistryquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='englishquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='physicsquestion',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
