# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-05 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20170721_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MathTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mathquestion',
            name='exam',
        ),
        migrations.AddField(
            model_name='mathset',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MathTopic'),
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='belongsTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.MathSet'),
        ),
    ]
