# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-05 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_mathtopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathtopic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
