# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-25 21:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_mathanswer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(default=' ', max_length=200, verbose_name=(b'Math', b'English')),
            preserve_default=False,
        ),
    ]
