# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-25 21:55
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_userdetail_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'MA', b'Math'), (b'EN', b'English')], max_length=5),
        ),
    ]
